/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.rs", "./index.html", "./style/**/*.{css,scss}"],
  darkMode: "class",
  safelist: [
    // Dynamic classes for drag-and-drop
    "border-theme",
    "border-accent-primary",
    "border-theme-secondary",
    // Accent color classes
    "bg-accent-primary",
    "bg-accent-primary-hover",
    "hover:bg-accent-primary-hover",
    "text-accent-primary",
    "hover:text-accent-primary",
    "shadow-accent-primary/25",
    "hover:shadow-accent-primary/25",
    "bg-accent-primary/5",
    "bg-accent-primary/10",
    "bg-accent-primary/20",
    "ring-accent-primary",
    "focus:ring-accent-primary",
    "bg-blue-100",
    "dark:bg-blue-900",
    "bg-opacity-10",
    // Dynamic classes for landing page animations
    "rotate-180",
    "animate-bounce",
    "pointer-events-none",
    "pointer-events-auto",
    "animate-spin",
    "animate-fade-in-up",
    "animation-delay-200",
    "animation-delay-400",
    "visible",
    // Button styling for light/dark themes
    "bg-white",
    "bg-gray-50",
    "dark:bg-gray-800",
    "dark:bg-gray-900",
    "border-gray-300",
    "border-gray-400",
    "dark:border-gray-500",
    "dark:border-gray-600",
    "hover:bg-gray-100",
    "hover:bg-gray-200",
    "dark:hover:bg-gray-700",
    "dark:hover:bg-gray-800",
    "text-gray-600",
    "text-gray-700",
    "dark:text-gray-200",
    "dark:text-gray-300",
    "hover:text-gray-900",
    "dark:hover:text-white",
    // AI demo animation classes
    "ai-demo-container",
    "ai-message-1",
    "ai-message-3",
    "ai-message-4",
    "ai-thinking",
    "ai-user-typing",
    "ai-content-line-1",
    "ai-content-line-2",
    "ai-content-line-3",
    "ai-content-line-4",
    "ai-content-line-5",
    "ai-content-line-6",
    // Visual editor animation
    "visual-editor-container",
    // Collaboration animation
    "collab-table-left",
    "collab-table-right",
    "collab-cursor-alice-inner",
    "collab-cursor-bob-inner",
    "collab-connection",
    "collab-relation-group",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["Fira Code", "monospace"],
      },
      boxShadow: {
        node: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
        "node-hover":
          "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
        "node-dark":
          "0 4px 6px -1px rgba(0, 0, 0, 0.3), 0 2px 4px -1px rgba(0, 0, 0, 0.2)",
        "node-hover-dark":
          "0 10px 15px -3px rgba(0, 0, 0, 0.3), 0 4px 6px -2px rgba(0, 0, 0, 0.15)",
      },
      cursor: {
        grab: "grab",
        grabbing: "grabbing",
      },
      backgroundColor: {
        "dark-primary": "#1a1a2e",
        "dark-secondary": "#16213e",
        "dark-surface": "#0f0f23",
        "dark-card": "#1e1e3f",
      },
      borderColor: {
        "dark-border": "#2d2d5a",
      },
    },
  },
  plugins: [],
};
